my_car_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls'))
]

my_car_site/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f"Car is {self.brand} {self.year}"
    

my_car_site/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context = {
        'all_cars': all_cars
    }

    return render(request, 'cars/list.html', context=context)
    
def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])

        models.Car.objects.create(brand=brand, year=year)

        return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/add.html')

def delete(request):
    if request.POST:
        pk = request.POST['pk']
        try:
             models.Car.objects.get(pk=pk).delete()
             return redirect(reverse('cars:list'))
        except:
            print('pk not found')
            return redirect(reverse('cars:list'))

       
        
    else:
        return render(request, 'cars/delete.html')

my_car_site/cars/templates/cars/add.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>ADD.HTML</h1>
  <h2>Add a new car to the database</h2>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="brand">Brand:</label>
      <input type="text" id="brand" name="brand" class="form-control" />
    </div>

    <div class="form-group">
      <label for="year">Year:</label>
      <input type="text" name="year" id="year" class="form-control" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

{% endblock content %}

my_car_site/cars/templates/cars/delete.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <h1>DELETE.HTML</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="pk">PK Number:</label>
      <input
        type="text"
        name="pk"
        id="pk"
        class="form-control"
        placeholder="pk"
        aria-describedby="enter primary key"
      />
      <small id="enter primary key" class="text-muted"></small>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

my_car_site/cars/templates/cars/list.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1>LIST.HTML</h1>
  <ul>
    {% for car in all_cars %}
    <li>{{car}}</li>
    {% endfor %}
  </ul>
</div>

{% endblock content %}

my_car_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
    <title>Document</title>
  </head>
  <body>
    {% comment %} NAVBAR {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cars:list' %}">List</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cars:add' %}">Add</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cars:delete' %}">Delete</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock content %}
  </body>
</html>